// Code generated by "stringer -type=NSearchType"; DO NOT EDIT

package structs

import "fmt"

const _NSearchType_name = "NSTUnknownNSTLocationNSTDeviceID"

var _NSearchType_index = [...]uint8{0, 10, 21, 32}

func (i NSearchType) String() string {
	if i < 0 || i >= NSearchType(len(_NSearchType_index)-1) {
		return fmt.Sprintf("NSearchType(%d)", i)
	}
	return _NSearchType_name[_NSearchType_index[i]:_NSearchType_index[i+1]]
}
