// Code generated by "stringer -type=NRequestType"; DO NOT EDIT

package structs

import "fmt"

const _NRequestType_name = "NRTUnknownNRTServicesAllNRTServicesAreaNRTCreateNRTSearchLLNRTSearchDID"

var _NRequestType_index = [...]uint8{0, 10, 24, 39, 48, 59, 71}

func (i NRequestType) String() string {
	if i < 0 || i >= NRequestType(len(_NRequestType_index)-1) {
		return fmt.Sprintf("NRequestType(%d)", i)
	}
	return _NRequestType_name[_NRequestType_index[i]:_NRequestType_index[i+1]]
}
