// Code generated by "stringer -type=searchType"; DO NOT EDIT

package request

import "fmt"

const _searchType_name = "srchtUnknownsrchtReportIDsrchtDeviceIDstchtLatLng"

var _searchType_index = [...]uint8{0, 12, 25, 38, 49}

func (i searchType) String() string {
	if i < 0 || i >= searchType(len(_searchType_index)-1) {
		return fmt.Sprintf("searchType(%d)", i)
	}
	return _searchType_name[_searchType_index[i]:_searchType_index[i+1]]
}
